"""add_reports_and_audit_logs

Revision ID: 58398eea5e00
Revises: 60129fb6c6f1
Create Date: 2025-08-30 19:20:41.620587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58398eea5e00'
down_revision = '60129fb6c6f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
