"""fix_email_constraint_tenant_scoped

Revision ID: 60129fb6c6f1
Revises: 447dbb47aa6f
Create Date: 2025-08-30 18:49:32.865263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60129fb6c6f1'
down_revision = '447dbb47aa6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_email_tenant', 'users', ['email', 'tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email_tenant', table_name='users')
    # ### end Alembic commands ###
