"""add summary and findings_json to reports

Revision ID: 830883bcbc0e
Revises: 720883bcbc0d
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '830883bcbc0e'
down_revision = '720883bcbc0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('findings_json', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'findings_json')
    op.drop_column('reports', 'summary')
    # ### end Alembic commands ###
